import test from "node:test";
import assert from "node:assert/strict";
import crypto from "crypto";
import fs from "fs";
import path from "path";
import prisma from "../lib/prisma.js";
import { tvTempUploadDir, tvUploadDir } from "../config/uploads.js";
import {
  detectFileType,
  makeSafeStoredFileName,
  TV_MEDIA_MIMES,
  validateDeclaredFile,
  validateMagicBytes,
  VISITOR_IMAGE_MIMES,
} from "./fileSecurity.js";
import { createTvContent } from "../controllers/tvContent.controller.js";

const PNG_BYTES = Buffer.from([
  0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0x00, 0x00, 0x00, 0x0d,
]);

function createRes() {
  return {
    statusCode: 200,
    body: undefined,
    status(code) {
      this.statusCode = code;
      return this;
    },
    json(body) {
      this.body = body;
      return this;
    },
  };
}

function listFiles(dir) {
  return new Set(fs.existsSync(dir) ? fs.readdirSync(dir) : []);
}

function withPrismaMocks(mocks, fn) {
  const originals = [];

  for (const [model, methods] of Object.entries(mocks)) {
    for (const [method, replacement] of Object.entries(methods)) {
      originals.push([model, method, prisma[model][method]]);
      prisma[model][method] = replacement;
    }
  }

  return Promise.resolve()
    .then(fn)
    .finally(() => {
      for (const [model, method, original] of originals.reverse()) {
        prisma[model][method] = original;
      }
    });
}

test("detectFileType recognizes allowed image signatures", () => {
  assert.deepEqual(detectFileType(Buffer.from([0xff, 0xd8, 0xff, 0x00])), {
    mime: "image/jpeg",
    ext: ".jpg",
  });
  assert.deepEqual(detectFileType(PNG_BYTES), { mime: "image/png", ext: ".png" });
});

test("allowed extension with incompatible content is rejected", () => {
  const result = validateMagicBytes(
    {
      originalname: "foto.jpg",
      mimetype: "image/jpeg",
      buffer: Buffer.from("<html></html>"),
    },
    VISITOR_IMAGE_MIMES
  );

  assert.equal(result.ok, false);
  assert.equal(result.statusCode, 415);
});

test("dangerous names and double extensions are rejected before storage", () => {
  const traversal = validateDeclaredFile(
    { originalname: "../foto.jpg", mimetype: "image/jpeg" },
    VISITOR_IMAGE_MIMES
  );
  const doubleExtension = validateDeclaredFile(
    { originalname: "foto.jpg.exe", mimetype: "image/jpeg" },
    VISITOR_IMAGE_MIMES
  );
  const html = validateDeclaredFile(
    { originalname: "banner.html", mimetype: "text/html" },
    TV_MEDIA_MIMES
  );

  assert.equal(traversal.ok, false);
  assert.equal(doubleExtension.ok, false);
  assert.equal(html.ok, false);
});

test("safe stored names are generated by the server and do not collide", () => {
  const first = makeSafeStoredFileName("image/png");
  const second = makeSafeStoredFileName("image/png");

  assert.match(first, /^[0-9a-f-]{36}\.png$/);
  assert.match(second, /^[0-9a-f-]{36}\.png$/);
  assert.notEqual(first, second);
});

test("createTvContent removes promoted TV file when database write fails", async () => {
  fs.mkdirSync(tvTempUploadDir, { recursive: true });
  fs.mkdirSync(tvUploadDir, { recursive: true });

  const beforeTv = listFiles(tvUploadDir);
  const beforeTemp = listFiles(tvTempUploadDir);
  const tempPath = path.join(tvTempUploadDir, `${crypto.randomUUID()}.upload`);
  fs.writeFileSync(tempPath, PNG_BYTES);

  const req = {
    body: {
      title: "Teste",
      order: "0",
      isActive: "true",
      branchIds: "[1]",
    },
    file: {
      path: tempPath,
      originalname: "banner.png",
      mimetype: "image/png",
      size: PNG_BYTES.length,
    },
    user: { id: 1 },
  };
  const res = createRes();
  const originalTransaction = prisma.$transaction;
  const originalConsoleError = console.error;
  prisma.$transaction = async () => {
    throw new Error("db fail");
  };
  console.error = () => {};

  try {
    await withPrismaMocks(
      {
        branch: {
          findMany: async () => [{ id: 1 }],
        },
      },
      () => createTvContent(req, res)
    );
  } finally {
    prisma.$transaction = originalTransaction;
    console.error = originalConsoleError;
  }

  assert.equal(res.statusCode, 500);
  assert.deepEqual(listFiles(tvUploadDir), beforeTv);
  assert.deepEqual(listFiles(tvTempUploadDir), beforeTemp);
});
